const poopCompliments = [
    "Wow, you're truly a gut health champion today! 💩",
    "Congrats on completing nature’s most essential task with grace!",
    "Your bowels deserve a standing ovation for that stellar performance!",
    "You’re the MVP of intestinal efficiency today. Bravo! 👏",
    "Nothing says success like a smooth and satisfying poop. Well done!",
    "You’re truly a master of digestive determination. Hats off! 🎩",
    "Your bathroom break deserves its own applause track. 👏💩",
    "That was a gut-wrenching success in the best way possible. Kudos!",
    "You just unlocked the ‘Bowel Movement Extraordinaire’ achievement!",
    "Your body just thanked you for that flawless execution. Bravo!",
    "You’re the hero your toilet needed today. 🦸‍♂️🦸‍♀️",
    "The way you handle your business is truly inspiring. 💪",
    "You just had a crappy moment… in the best possible way!",
    "Your digestive system is a well-oiled machine. Well played!",
    "Today’s poop is tomorrow’s success story. Keep thriving! 🚀",
    "That was an act of intestinal bravery. Salute to you! 🫡",
    "The toilet gods are proud of your offerings today!",
    "You’re setting the standard for regularity. Keep shining!",
    "Not all heroes wear capes; some just poop like champions.",
    "That’s a solid way to seize the day. Literally. 🌟",
    "Poop today, conquer the world tomorrow. You’re unstoppable!",
    "Your bathroom break deserves a standing ovation. Bravo! 👏",
    "You’re the Picasso of pooping—mastering the art beautifully!",
    "No clogs, no problems. You’re a true professional!",
    "You’ve officially won the bowel movement lottery today!",
    "Every flush is a victory, and you’re winning the game. 💪",
    "Your colon is celebrating your great achievement today!",
    "You’ve proven that a good poop is the foundation of a great day!",
    "If pooping was an Olympic sport, you’d take home gold. 🥇",
    "A round of applause for your bowels’ excellent teamwork!"
];

module.exports = poopCompliments;